version: '3'
services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - 27017:27017
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ./scripts:/scripts

  mongo2:
    image: mongo:latest
    container_name: mongo2
    ports:
      - 27018:27017
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ./scripts:/scripts

  mongo3:
    image: mongo:latest
    container_name: mongo3
    ports:
      - 27019:27017
    networks:
      - mongo-cluster
    command: --replSet rs0 --bind_ip_all
    volumes:
      - ./scripts:/scripts

networks:
  mongo-cluster:
    driver: bridge
